tests:
  name: ./test.sh
  runs-on: ${{ matrix.os }}
  strategy:
    fail-fast: false
    matrix:
      include:
        - os: ${{ github.repository == 'commaai/opendbc' && 'namespace-profile-amd64-8x16' || 'ubuntu-24.04' }}
        - os: ${{ github.repository == 'commaai/opendbc' && 'namespace-profile-macos-8x14' || 'macos-latest' }}

  steps:
  - uses: actions/checkout@v4
    with:
      repository: 'mvl-boston/openpilot'
      ref: ${{ env.PARENT_MVL_BRANCH }}
      submodules: true

  - run: ./tools/op.sh setup

  - run: rm -rf opendbc_repo/

  - uses: actions/checkout@v4
    with:
      path: opendbc_repo

  - name: Cache test routes
    id: routes-cache
    uses: actions/cache@v4
    with:
      path: /tmp/comma_download_cache
      key: car_models-${{ hashFiles('selfdrive/car/tests/test_models.py', 'opendbc/car/tests/routes.py') }}-${{ matrix.job }}

  - name: Build openpilot
    run: scons -j1 common/ cereal/ selfdrive/pandad/ msgq_repo/ opendbc_repo

  - name: ./test.sh
    timeout-minutes: ${{ contains(runner.name, 'nsc') && (steps.routes-cache.outputs.cache-hit == 'true') && 2 || 999 }}
    run: opendbc_repo/test.sh
    env:
      PYTHONPATH: ${{ github.workspace }}/openpilot:${{ github.workspace }}
